version: "3.8"

services:
  grafana-container:
    image: grafana/grafana-enterprise
    volumes:
      - "./provision.yml:/etc/grafana/provisioning/dashboards/provision.yml"
      - "./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
      - "./dashboards:/var/lib/grafana/dashboards"
    ports:
      - "3000:3000"
    environment:
      ds-prometheus: Prometheus
  prometheus-container:
    restart: unless-stopped
    image: prom/prometheus
    volumes:
      - "./.data/prometheus-data:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  # node-exporter-container:
  #   image: prom/node-exporter
  #   ports:
  #     - "9100:9100"
  # node-exporter-container2:
  #   image: prom/node-exporter
  #   ports:
  #     - "9101:9101"

  # influxdb-container:
  #   image: influxdb
  #   volumes:
  #     - "./.data/influxdb:/var/lib/influxdb2"
  #     - "./config:/etc/influxdb2"
  #   ports:
  #     - "25000:25000"
  #   environment:
  #     DOCKER_INFLUXDB_INIT_MODE: setup
  #     DOCKER_INFLUXDB_INIT_USERNAME: user
  #     DOCKER_INFLUXDB_INIT_PASSWORD: 1
  #     DOCKER_INFLUXDB_INIT_ORG: org
  #     DOCKER_INFLUXDB_INIT_BUCKET: bucket
