version: "3.8"

services:
  grafana-container:
    image: grafana/grafana-enterprise
    volumes:
      - "./provision.yml:/etc/grafana/provisioning/dashboards/provision.yml"
      - "./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
      - "./dashboards:/var/lib/grafana/dashboards"
    ports:
      - "3000:3000"
    environment:
      ds-prometheus: Prometheus
  prometheus-container:
    restart: unless-stopped
    image: prom/prometheus
    volumes:
      - "./.data/prometheus-data:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
