global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets: ["localhost:9090"]
# - job_name: "node-exporter"
#   metrics_path: "/metrics"
#   static_configs:
#   - targets: ["host.docker.internal:9100"]
# - job_name: "node-exporter2"
#   metrics_path: "/metrics"
#   static_configs:
#   - targets: ["host.docker.internal:9101"]
- job_name: "metric"
  metrics_path: "/actuator/prometheus"
  static_configs:
  - targets:
    # Spring Public IP on GCP
    - "host.docker.internal:9999"
